### ISSUE TITLE
Build/install instructions

### ISSUE THREAD

**Issue by casmbu** [orzgithub/omega-de-kernel_ZaindORp#1]
Any chance you could update the build and install instructions? When I build, the ezkernelnew.bin file doesn't get updated and the jagoomba version currently in the kernel is 0.4a. I'm not sure how to link the files in this repository. The old Link_kernel_image.exe doesn't work. I'm not sure how to install this after building it. Thanks in advance!

**Comment by orzgithub** [comment]
ZaindORp guess you know how to build the kernel so it's not necessary to tell how to build right? After that you'll get omega-de-kernel_ZaindORp.gba(or other files with an extension of gba, depending on the name of the folder) and that's what you need. Just rename that as ezkernelnew.bin and install it. Different from the official source this modded version doesn't need to be built with Link_kernel_image.exe because resource packs are hard-coded with source. But you can convert pictures in your theme with [Grit](http://www.coranac.com/projects/#grit) and replace the original one in ``src/images.c``. But building a replaceable theme file is a better idea if you wish to use a different theme.

**Comment by casmbu** [comment]
Thank you!
